#####################
##     Example     ##
#####################

#  [TVDb number]: # [Name of show]
#    title: [Name of show]
#    alt_title: [it's sometimes also called...]
#    sort_title: [how to sort show]
#    url_poster: https://theposterdb.com/api/assets/[poster-number]

#################################################
##     Plex Auto-naming and Metadata Fixes     ##
#################################################

metadata:

  283468: # Star Wars Rebels
    seasons:
      1:
        episodes:
          0:
            title: Spark Of Rebellion
      2:
        episodes:
          0:
            title: Siege Of Lothal